mode: ContinuousDeployment
assembly-informational-format: '{Major}.{Minor}.{Patch}-{PreReleasetag-prefix}-{ShortSha}'
branches:
  master:
    regex: '^master$|^main$'
    mode: ContinuousDeployment
    tag-prefix: 'rc'
    increment: Inherit
  develop:
    regex: '^dev(elop)?(ment)?$'
    mode: ContinuousDeployment
    tag-prefix: 'unstable'
    increment: Inherit
  feature:
    regex: '^features?[/-](?<BranchName>.+)$'
    mode: ContinuousDeployment
    tag-prefix: '{BranchName}'
    increment: Inherit
  hotfix:
    regex: '^hotfix(es)?[/-](?<BranchName>.+)$'
    mode: ContinuousDeployment
    tag-prefix: 'beta'
    increment: None
  release:
    regex: '^releases?[/-](?<Version>\d+\.\d+\.\d+)$'
    mode: ContinuousDeployment
    tag-prefix: 'rc'
    increment: None
    is-release-branch: true
ignore:
  sha: []
merge-message-formats: {}