mode: ContinuousDeployment
assembly-informational-format: '{Major}.{Minor}.{Patch}-{PreReleaseLabel}-{ShortSha}'
branches:
  master:
    regex: '^master$|^main$'
    mode: ContinuousDeployment
    label: rc
    increment: Inherit
  develop:
    regex: '^dev(elop)?(ment)?$'
    mode: ContinuousDeployment
    label: unstable
    increment: None
  feature:
    regex: '^features?[/-](?<BranchName>.+)$'
    mode: ContinuousDeployment
    label: '{BranchName}'
    increment: None
  hotfix:
    regex: '^hotfix(es)?[/-](?<BranchName>.+)$'
    mode: ContinuousDeployment
    label: beta
    increment: None
  release:
    regex: '^releases?[/-](?<BranchName>.+)$'
    mode: ContinuousDeployment
    label: rc
    increment: None
ignore:
  sha: []
merge-message-formats: {}
