mode: ContinuousDeployment
assembly-informational-format: '{Major}.{Minor}.{Patch}-{PreReleaseLabel}-{ShortSha}'
branches:
  master:
    regex: ^master$|^main$
    mode: ContinuousDeployment
    label: ''
    increment: Inherit
    is-release-branch: true
  develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDeployment
    label: unstable
    increment: Inherit
  feature:
    regex: feature(s)?[/-]
    mode: ContinuousDeployment
    label: '{BranchName}'
    increment: Inherit
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDeployment
    label: beta
    increment: None
  release:
    regex: release(s)?[/-]
    mode: ContinuousDeployment
    label: rc
    increment: Inherit
    is-release-branch: true
ignore:
  sha: []
merge-message-formats: {}