mode: ContinuousDelivery
assembly-informational-format: '{Major}.{Minor}.{Patch}-{PreReleaseLabel}-{ShortSha}'
branches:
  release:
    regex: '^releases?[/-](?<Version>\d+\.\d+\.\d+)'
    mode: ContinuousDelivery
    label: rc
    increment: None
    is-release-branch: true
  master:
    regex: ^master$|^main$
    mode: ContinuousDeployment
    label: ''
    increment: Inherit
    is-release-branch: true
  develop:
    regex: dev(elop)?(ment)?$
    mode: ContinuousDelivery
    label: unstable
    increment: Inherit
  feature:
    regex: feature(s)?[/-]
    mode: ContinuousDelivery
    label: 'feature'
    increment: Inherit
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDelivery
    label: beta
    increment: None
ignore:
  sha: []
merge-message-formats: {}